### ISSUE TITLE
Change direction on swipe

### ISSUE THREAD

**Issue by gimesi** [PolarNotion/turntable-slider#4]
Hi! This is no "issue" in the strict sense, just found it a bit counter-intuitive when swiping e.g. from left to right on the demo, and the image is rotating the other way round. Surely depends on what kind of image you want to rotate but it might be a nice advancement to be able to reverse the rotation. Nice script :)

**Comment by alxngyn** [comment]
I think the inversion should be toggle-able via a parameter in JS.

**Comment by morganjlopes** [comment]
@gimesi Thanks for the heads up. Should be working correctly now. @alxngyn great feedback, we've got a few shiny new options coming soon.
